### ISSUE TITLE
Semantics

### ISSUE THREAD

**Issue by am548726** [drexnexlo/mix-a-lot#1]
# Semantics
## Naming Conventions
- A possible route to have a easier time finding the type of images in your image folder is to name them accordingly to what they are going to be used for. Example is _hero-lg-cupcakes_ instead of cupcakes
- There seems to be a untitled section when I checked in https://gsnedders.html5.org/outliner/ you could fix this by giving it a proper name.
- As for css naming and targeting specific elements I think you could target for example the header instead of giving it a class of main-header. Your custom css should override the styling from foundation's stylesheet since yours is below it in the head section in the html document.

**Comment by MatthewCThompson** [comment]
Some class names could be more simple. For example, in the header there is a class used "main-header" this can be "navigation-header" or just "header" since there is only one class with the name header in it.
