### ISSUE TITLE
User Experience

### ISSUE THREAD

**Issue by slaterjen** [drexnexlo/mix-a-lot#3]
Advanced! Everything seemed to look good.

**Comment by SpicyKeeKay** [comment]
Overall I feel that the site is understandable. The gallery is kind of weird with the way the pictures will be laid out. It leaves a lot of weird white space. Is there gonna be social media icons, cause it says social media icons in in the nav.

**Comment by kaylabrinkerhoff** [comment]
Satisfactory. Your gallery images are placed awkwardly. I didn't even see the social media area in the nav at first. Other than that, I'm excited to see it when its done.
